---
name: Main
"on": push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - uses: actions/checkout@v1
      - name: Build
        run: |
          make build
  docker:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker
        run: |
          make docker
          make push
